name: NFL Rushing

on: [push]

env:
  MIX_ENV: test
  DB_HOST: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: postgres

jobs:
  test:
    name: Phoenix testing with ExUnit
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.12"
          otp-version: "24"
          experimental-otp: true
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}
          path: |
            deps
            _build
            priv/plts
      - name: Install Phoenix dependencies
        run: |
          mix deps.get
          mix deps.compile
      - name: Run Tests
        run: mix test --trace --color
